version: '3.9'

services:
  mongodb:
    image: mongo:5
    cpus: 1
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: articles
      MONGO_INITDB_ROOT_PASSWORD: articles
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
